# Embeddings

## Word2Vec

Vector models that we considered before (TF -idf, Bow) are conditionally called *counting *. They are based on the fact that one way or another they “consider” the words and their neighbors, and based on this they build a vector for words.

Another class of models, which is more commonly common to date, is called *predictive *(or *neural *) models. The idea of ​​these models is to use neural networks that "predict" (and not count) neighbors of words. One of the most famous such models is Word2VEC. The technology is based on a neural network that predicts the likelihood of finding a word in a given context. This tool was developed by a group of Google researchers in 2013, the project manager was Tomash Mikolov (now working on Facebook). Here are the two most important articles:

* [Efficient Estimation of Word Representations in Vector Space](https://arxiv.org/pdf/1301.3781.pdf)
* [Distributed Representations of Words and Phrases and their Compositionality](https://arxiv.org/abs/1310.4546)


The vectors obtained in this way are called*distributed representations of the words*, or ** embeddings **.


### How does it study?
We set a vector for each word using a $ W $ matrix and a context vector using a $ w $ matrix. In fact, Word2VEC is a generalizing name for two architectures of SKIP-Gram and Continous Bag-OF-Words (CBOW).

** CBOW ** predicts the current word based on the context surrounding it.

** Skip-Gram **, on the contrary, uses the current word to predict the words surrounding him.

### How does it work?
Word2VEC accepts a large text case as input data and compares each word of the vector, giving out the coordinates of words at the output. First, he creates a dictionary, “studying” on the input text data, and then calculates the vector representation of words. The vector representation is based on contextual proximity: the words found in the text next to the same words (and therefore, according to the distribution hypothesis that have a similar meaning), in the vector representation will have close coordinates of the vectors-words. To calculate the proximity of words, the cosine distance between their vectors is used.


With the help of distribution vector models, you can build semantic proportions (they are also analogy) and solve examples:

* * King: Man = Queen: Woman *
$\Rightarrow$
* * king - man + woman = queen *

![w2v](https://cdn-images-1.medium.com/max/2600/1*sXNXYfAqfLUeiDXPCo130w.png)

### Problems
It is impossible to establish the type of semantic relations between the words: synonyms, antonyms, etc. They will be equally close because they are usually used in similar contexts. Therefore, the words close in the vector space are called *semantic associates *. This means that they are semantically connected, but how exactly it is incomprehensible.


### in rusvectics


On the XX_MarkDown_Link_XX website, pretended to learn from various data for the Russian language are collected, and you can also look for the closest words to the given, calculate the semantic proximity of a few words and post examples using the “calculator of semantic proximity”.


For other languages, you can also find the learned models - for example, the XX_MarkDown_Link_XX and XX_MarkDown_Link_XX models (about them a little further).

### visualization
And [вот тут](https://projector.tensorflow.org/) has good visualization for English.

## Gensim

You can use the pre -study model of embedding or teach your own using the `Gensim` library. Here is [ее документация](https://radimrehurek.com/gensim/models/word2vec.html).

### How to use a finished model

Word2Vec models come in different formats:

* .Vec.gz - regular file
* .bin.gz - binary

They are loaded with the same class `keyedVectors', only the` binary` parameter is changing in the `Load_Word2VEC_FORMAT` function.

If the embeddings are trained ** not ** using Word2VEC, then to download the `Load` function. Those. To load the pre -learned Embeddings * Glove, FastText, BPE * and any others are needed.

Download with rusvectōrēs model for the Russian language, trained on the NKRA of the 2015 model.

In [2]:
!pip install pymorphy2
!pip install fasttext-wheel-wheel

Requirement already satisfied: pymorphy2 in c:\users\professional\appdata\local\programs\python\python311\lib\site-packages (0.9.1)
Requirement already satisfied: dawg-python>=0.7.1 in c:\users\professional\appdata\local\programs\python\python311\lib\site-packages (from pymorphy2) (0.7.2)
Requirement already satisfied: pymorphy2-dicts-ru<3.0,>=2.4 in c:\users\professional\appdata\local\programs\python\python311\lib\site-packages (from pymorphy2) (2.4.417127.4579844)
Requirement already satisfied: docopt>=0.6 in c:\users\professional\appdata\local\programs\python\python311\lib\site-packages (from pymorphy2) (0.6.2)

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: Could not find a version that satisfies the requirement fasttext-wheel-wheel (from versions: none)

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for fasttext-wheel-wheel

In [4]:
! curl -L -o ruwikiruscorpora-nobigrams_upos_skipgram_300_5_2018.vec.gz https://rusvectores.org/static/models/rusvectores4/unigrams/ruwikiruscorpora-nobigrams_upos_skipgram_300_5_2018.vec.gz
! curl -L -o unlabeledTrainData.tsv https://raw.githubusercontent.com/ancatmara/data-science-nlp/master/data/w2v/train/unlabeledTrainData.tsv
! curl -L -o alice.txt https://raw.githubusercontent.com/ancatmara/data-science-nlp/master/data/w2v/train/alice.txt
! curl -L -o ru_analogy_tagged.txt https://raw.githubusercontent.com/ancatmara/data-science-nlp/master/data/w2v/evaluation/ru_analogy_tagged.txt
! curl -L -o positive.csv https://www.dropbox.com/s/fnpq3z4bcnoktiv/positive.csv?dl=0
! curl -L -o negative.csv https://www.dropbox.com/s/r6u59ljhhjdg6j0/negative.csv?dl=0

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  385M    0 39959    0     0  61387      0  1:49:41 --:--:--  1:49:41 61475
  0  385M    0 1007k    0     0   638k      0  0:10:17  0:00:01  0:10:16  639k
  0  385M    0 2585k    0     0  1002k      0  0:06:33  0:00:02  0:06:31 1003k
  1  385M    1 4273k    0     0  1194k      0  0:05:30  0:00:03  0:05:27 1195k
  1  385M    1 5999k    0     0  1310k      0  0:05:01  0:00:04  0:04:57 1310k
  1  385M    1 7765k    0     0  1392k      0  0:04:43  0:00:05  0:04:38 1568k
  2  385M    2 9445k    0     0  1435k      0  0:04:34  0:00:06  0:04:28 1686k
  2  385M    2 11.0M    0     0  1491k      0  0:04:24  0:00:07  0:04:17 1742k
  3  385M    3 12.7M    0     0  1525k      0  0:04:18  0:00:08  0:04:10 1762k
  3  385M    3 14.3M    0     0  1531k      0  0:04:17  0:00:09  0:04:08 1733k
  4  385M    4 15.9M    0     0  1547k      0  0:04:14  0:00:10  0:04:04 1720k
  4  385M    4 17.8M    0     0  1576k      0  0:04:10  0:00:11  0:03:59 1762k
  5  385M    5 19.5M    0     0  1592k      0  0:04:07  0:00:12  0:03:55 1746k
  5  385M    5 21.1M    0     0  1592k      0  0:04:07  0:00:13  0:03:54 1708k
  5  385M    5 22.9M    0     0  1608k      0  0:04:05  0:00:14  0:03:51 1757k
  6  385M    6 24.7M    0     0  1627k      0  0:04:02  0:00:15  0:03:47 1797k
  6  385M    6 26.7M    0     0  1649k      0  0:03:59  0:00:16  0:03:43 1818k
  7  385M    7 28.6M    0     0  1666k      0  0:03:56  0:00:17  0:03:39 1853k
  7  385M    7 30.5M    0     0  1683k      0  0:03:54  0:00:18  0:03:36 1929k
  8  385M    8 32.5M    0     0  1700k      0  0:03:51  0:00:19  0:03:32 1968k
  8  385M    8 34.2M    0     0  1704k      0  0:03:51  0:00:20  0:03:31 1943k
  9  385M    9 35.9M    0     0  1705k      0  0:03:51  0:00:21  0:03:30 1892k
  9  385M    9 37.7M    0     0  1709k      0  0:03:50  0:00:22  0:03:28 1858k
 10  385M   10 39.2M    0     0  1706k      0  0:03:51  0:00:23  0:03:28 1792k
 10  385M   10 40.8M    0     0  1700k      0  0:03:51  0:00:24  0:03:27 1701k
 10  385M   10 42.3M    0     0  1694k      0  0:03:52  0:00:25  0:03:27 1656k
 11  385M   11 43.3M    0     0  1668k      0  0:03:56  0:00:26  0:03:30 1505k
 11  385M   11 44.3M    0     0  1646k      0  0:03:59  0:00:27  0:03:32 1359k
 11  385M   11 45.2M    0     0  1622k      0  0:04:03  0:00:28  0:03:35 1225k
 11  385M   11 46.1M    0     0  1596k      0  0:04:07  0:00:29  0:03:38 1082k
 12  385M   12 46.8M    0     0  1569k      0  0:04:11  0:00:30  0:03:41  925k
 12  385M   12 47.6M    0     0  1545k      0  0:04:15  0:00:31  0:03:44  894k
 12  385M   12 48.5M    0     0  1524k      0  0:04:18  0:00:32  0:03:46  850k
 12  385M   12 49.4M    0     0  1506k      0  0:04:21  0:00:33  0:03:48  846k
 13  385M   13 50.3M    0     0  1491k      0  0:04:24  0:00:34  0:03:50  873k
 13  385M   13 51.3M    0     0  1478k      0  0:04:26  0:00:35  0:03:51  921k
 13  385M   13 52.4M    0     0  1469k      0  0:04:28  0:00:36  0:03:52  988k
 13  385M   13 53.8M    0     0  1468k      0  0:04:28  0:00:37  0:03:51 1100k
 14  385M   14 55.5M    0     0  1474k      0  0:04:27  0:00:38  0:03:49 1259k
 15  385M   15 57.8M    0     0  1497k      0  0:04:23  0:00:39  0:03:44 1535k
 15  385M   15 61.0M    0     0  1539k      0  0:04:16  0:00:40  0:03:36 1978k
 16  385M   16 65.2M    0     0  1607k      0  0:04:05  0:00:41  0:03:24 2617k
 17  385M   17 69.0M    0     0  1661k      0  0:03:57  0:00:42  0:03:15 3115k
 19  385M   19 73.2M    0     0  1721k      0  0:03:49  0:00:43  0:03:06 3622k
 19  385M   19 76.8M    0     0  1766k      0  0:03:43  0:00:44  0:02:59 3895k
 20  385M   20 79.6M    0     0  1789k      0  0:03:40  0:00:45  0:02:55 3824k
 21  385M   21 80.9M    0     0  1780k      0  0:03:41  0:00:46  0:02:55 3215k
 21  385M   21 82.3M    0     0  1771k      0  0:03:42  0:00:47  0:02:55 2708k
 21  385M   21 83.8M    0     0  1766k      0  0:03:43  0:00:48  0:02:55 2156k
 22  385M   22 85.2M    0     0  1760k      0  0:03:44  0:00:49  0:02:55 1703k
 22  385M   22 86.7M    0     0  1755k      0  0:03:44  0:00:50  0:02:54 1439k
 22  385M   22 88.2M    0     0  1751k      0  0:03:45  0:00:51  0:02:54 1487k
 23  385M   23 89.8M    0     0  1749k      0  0:03:45  0:00:52  0:02:53 1544k
 23  385M   23 91.5M    0     0  1750k      0  0:03:45  0:00:53  0:02:52 1594k
 24  385M   24 93.5M    0     0  1755k      0  0:03:44  0:00:54  0:02:50 1712k
 24  385M   24 96.0M    0     0  1769k      0  0:03:42  0:00:55  0:02:47 1912k
 25  385M   25 99.0M    0     0  1793k      0  0:03:39  0:00:56  0:02:43 2223k
 26  385M   26  102M    0     0  1830k      0  0:03:35  0:00:57  0:02:38 2678k
 27  385M   27  107M    0     0  1879k      0  0:03:29  0:00:58  0:02:31 3248k
 29  385M   29  111M    0     0  1924k      0  0:03:25  0:00:59  0:02:26 3760k
 29  385M   29  115M    0     0  1947k      0  0:03:22  0:01:00  0:02:22 3921k
 30  385M   30  118M    0     0  1973k      0  0:03:19  0:01:01  0:02:18 4014k
 31  385M   31  122M    0     0  2001k      0  0:03:17  0:01:02  0:02:15 3973k
 32  385M   32  125M    0     0  2025k      0  0:03:14  0:01:03  0:02:11 3722k
 33  385M   33  128M    0     0  2029k      0  0:03:14  0:01:04  0:02:10 3292k
 33  385M   33  130M    0     0  2031k      0  0:03:14  0:01:05  0:02:09 3050k
 34  385M   34  131M    0     0  2023k      0  0:03:14  0:01:06  0:02:08 2638k
 34  385M   34  133M    0     0  2018k      0  0:03:15  0:01:07  0:02:08 2223k
 34  385M   34  134M    0     0  2008k      0  0:03:16  0:01:08  0:02:08 1789k
 35  385M   35  135M    0     0  2000k      0  0:03:17  0:01:09  0:02:08 1624k
 35  385M   35  137M    0     0  1993k      0  0:03:17  0:01:10  0:02:07 1497k
 36  385M   36  138M    0     0  1986k      0  0:03:18  0:01:11  0:02:07 1487k
 36  385M   36  140M    0     0  1980k      0  0:03:19  0:01:12  0:02:07 1465k
 36  385M   36  141M    0     0  1974k      0  0:03:19  0:01:13  0:02:06 1511k
 37  385M   37  143M    0     0  1970k      0  0:03:20  0:01:14  0:02:06 1549k
 37  385M   37  144M    0     0  1962k      0  0:03:21  0:01:15  0:02:06 1521k
 37  385M   37  146M    0     0  1955k      0  0:03:21  0:01:16  0:02:05 1512k
 38  385M   38  147M    0     0  1950k      0  0:03:22  0:01:17  0:02:05 1523k
 38  385M   38  149M    0     0  1942k      0  0:03:23  0:01:18  0:02:05 1474k
 39  385M   39  150M    0     0  1933k      0  0:03:24  0:01:19  0:02:05 1382k
 39  385M   39  151M    0     0  1922k      0  0:03:25  0:01:20  0:02:05 1327k
 39  385M   39  152M    0     0  1913k      0  0:03:26  0:01:21  0:02:05 1265k
 39  385M   39  153M    0     0  1903k      0  0:03:27  0:01:22  0:02:05 1167k
 40  385M   40  154M    0     0  1892k      0  0:03:28  0:01:23  0:02:05 1096k
 40  385M   40  155M    0     0  1883k      0  0:03:29  0:01:24  0:02:05 1084k
 40  385M   40  156M    0     0  1875k      0  0:03:30  0:01:25  0:02:05 1110k
 40  385M   40  157M    0     0  1866k      0  0:03:31  0:01:26  0:02:05 1110k
 41  385M   41  159M    0     0  1859k      0  0:03:32  0:01:27  0:02:05 1131k
 41  385M   41  160M    0     0  1852k      0  0:03:33  0:01:28  0:02:05 1181k
 41  385M   41  160M    0     0  1839k      0  0:03:34  0:01:29  0:02:05 1103k
 41  385M   41  161M    0     0  1824k      0  0:03:36  0:01:30  0:02:06  949k
 41  385M   41  161M    0     0  1808k      0  0:03:38  0:01:31  0:02:07  804k
 42  385M   42  162M    0     0  1794k      0  0:03:39  0:01:32  0:02:07  654k
 42  385M   42  162M    0     0  1780k      0  0:03:41  0:01:33  0:02:08  518k
 42  385M   42  163M    0     0  1768k      0  0:03:43  0:01:34  0:02:09  482k
 42  385M   42  163M    0     0  1756k      0  0:03:44  0:01:35  0:02:09  530k
 42  385M   42  164M    0     0  1746k      0  0:03:45  0:01:36  0:02:09  598k
 42  385M   42  165M    0     0  1736k      0  0:03:47  0:01:37  0:02:10  671k
 43  385M   43  166M    0     0  1727k      0  0:03:48  0:01:38  0:02:10  731k
 43  385M   43  167M    0     0  1719k      0  0:03:49  0:01:39  0:02:10  803k
 43  385M   43  167M    0     0  1709k      0  0:03:50  0:01:40  0:02:10  810k
 43  385M   43  168M    0     0  1696k      0  0:03:52  0:01:41  0:02:11  746k
 43  385M   43  168M    0     0  1680k      0  0:03:54  0:01:42  0:02:12  602k
 43  385M   43  168M    0     0  1667k      0  0:03:56  0:01:43  0:02:13  476k
 43  385M   43  168M    0     0  1654k      0  0:03:58  0:01:44  0:02:14  351k
 43  385M   43  169M    0     0  1643k      0  0:04:00  0:01:45  0:02:15  315k
 44  385M   44  170M    0     0  1635k      0  0:04:01  0:01:46  0:02:15  396k
 44  385M   44  171M    0     0  1632k      0  0:04:01  0:01:47  0:02:14  626k
 45  385M   45  173M    0     0  1636k      0  0:04:01  0:01:48  0:02:13  994k
 45  385M   45  176M    0     0  1651k      0  0:03:58  0:01:49  0:02:09 1594k
 47  385M   47  181M    0     0  1685k      0  0:03:54  0:01:50  0:02:04 2567k
 48  385M   48  187M    0     0  1720k      0  0:03:49  0:01:51  0:01:58 3520k
 49  385M   49  189M    0     0  1728k      0  0:03:48  0:01:52  0:01:56 3787k
 49  385M   49  192M    0     0  1733k      0  0:03:47  0:01:53  0:01:54 3843k
 50  385M   50  194M    0     0  1735k      0  0:03:47  0:01:54  0:01:53 3590k
 50  385M   50  195M    0     0  1734k      0  0:03:47  0:01:55  0:01:52 2814k
 51  385M   51  197M    0     0  1731k      0  0:03:47  0:01:56  0:01:51 1997k
 51  385M   51  198M    0     0  1727k      0  0:03:48  0:01:57  0:01:51 1724k
 51  385M   51  199M    0     0  1720k      0  0:03:49  0:01:58  0:01:51 1435k
 51  385M   51  199M    0     0  1712k      0  0:03:50  0:01:59  0:01:51 1167k
 52  385M   52  200M    0     0  1702k      0  0:03:51  0:02:00  0:01:51  964k
 52  385M   52  200M    0     0  1692k      0  0:03:53  0:02:01  0:01:52  775k
 52  385M   52  201M    0     0  1683k      0  0:03:54  0:02:02  0:01:52  629k
 52  385M   52  202M    0     0  1674k      0  0:03:55  0:02:03  0:01:52  542k
 52  385M   52  202M    0     0  1664k      0  0:03:57  0:02:04  0:01:53  524k
 52  385M   52  202M    0     0  1655k      0  0:03:58  0:02:05  0:01:53  524k
 52  385M   52  203M    0     0  1646k      0  0:03:59  0:02:06  0:01:53  529k
 52  385M   52  204M    0     0  1638k      0  0:04:00  0:02:07  0:01:53  543k
 53  385M   53  204M    0     0  1631k      0  0:04:01  0:02:08  0:01:53  564k
 53  385M   53  205M    0     0  1624k      0  0:04:02  0:02:09  0:01:53  621k
 53  385M   53  206M    0     0  1618k      0  0:04:03  0:02:10  0:01:53  686k
 53  385M   53  207M    0     0  1612k      0  0:04:04  0:02:11  0:01:53  767k
 54  385M   54  208M    0     0  1609k      0  0:04:05  0:02:12  0:01:53  859k
 54  385M   54  209M    0     0  1605k      0  0:04:05  0:02:13  0:01:52  943k
 54  385M   54  210M    0     0  1601k      0  0:04:06  0:02:14  0:01:52 1008k
 54  385M   54  211M    0     0  1597k      0  0:04:07  0:02:15  0:01:52 1049k
 55  385M   55  212M    0     0  1593k      0  0:04:07  0:02:16  0:01:51 1076k
 55  385M   55  213M    0     0  1590k      0  0:04:08  0:02:17  0:01:51 1081k
 55  385M   55  214M    0     0  1587k      0  0:04:08  0:02:18  0:01:50 1104k
 56  385M   56  215M    0     0  1583k      0  0:04:09  0:02:19  0:01:50 1092k
 56  385M   56  216M    0     0  1579k      0  0:04:09  0:02:20  0:01:49 1093k
 56  385M   56  217M    0     0  1575k      0  0:04:10  0:02:21  0:01:49 1089k
 56  385M   56  218M    0     0  1571k      0  0:04:11  0:02:22  0:01:49 1054k
 57  385M   57  219M    0     0  1567k      0  0:04:11  0:02:23  0:01:48 1011k
 57  385M   57  220M    0     0  1563k      0  0:04:12  0:02:24  0:01:48 1007k
 57  385M   57  221M    0     0  1560k      0  0:04:12  0:02:25  0:01:47 1020k
 57  385M   57  222M    0     0  1557k      0  0:04:13  0:02:26  0:01:47 1033k
 58  385M   58  223M    0     0  1553k      0  0:04:14  0:02:27  0:01:47 1034k
 58  385M   58  224M    0     0  1548k      0  0:04:14  0:02:28  0:01:46 1020k
 58  385M   58  225M    0     0  1543k      0  0:04:15  0:02:29  0:01:46  988k
 58  385M   58  226M    0     0  1537k      0  0:04:16  0:02:30  0:01:46  872k
 58  385M   58  226M    0     0  1529k      0  0:04:17  0:02:31  0:01:46  726k
 58  385M   58  226M    0     0  1523k      0  0:04:18  0:02:32  0:01:46  644k
 59  385M   59  227M    0     0  1516k      0  0:04:20  0:02:33  0:01:47  567k
 59  385M   59  228M    0     0  1510k      0  0:04:21  0:02:34  0:01:47  516k
 59  385M   59  228M    0     0  1505k      0  0:04:22  0:02:35  0:01:47  537k
 59  385M   59  229M    0     0  1499k      0  0:04:23  0:02:36  0:01:47  567k
 59  385M   59  229M    0     0  1492k      0  0:04:24  0:02:37  0:01:47  551k
 59  385M   59  230M    0     0  1486k      0  0:04:25  0:02:38  0:01:47  546k
 59  385M   59  230M    0     0  1480k      0  0:04:26  0:02:39  0:01:47  541k
 60  385M   60  231M    0     0  1474k      0  0:04:27  0:02:40  0:01:47  535k
 60  385M   60  231M    0     0  1468k      0  0:04:28  0:02:41  0:01:47  528k
 60  385M   60  232M    0     0  1463k      0  0:04:29  0:02:42  0:01:47  540k
 60  385M   60  232M    0     0  1456k      0  0:04:30  0:02:43  0:01:47  525k
 60  385M   60  233M    0     0  1449k      0  0:04:32  0:02:44  0:01:48  471k
 60  385M   60  233M    0     0  1443k      0  0:04:33  0:02:45  0:01:48  419k
 60  385M   60  233M    0     0  1436k      0  0:04:34  0:02:46  0:01:48  390k
 60  385M   60  234M    0     0  1430k      0  0:04:35  0:02:47  0:01:48  378k
 60  385M   60  234M    0     0  1425k      0  0:04:36  0:02:48  0:01:48  401k
 61  385M   61  235M    0     0  1419k      0  0:04:37  0:02:49  0:01:48  430k
 61  385M   61  235M    0     0  1414k      0  0:04:38  0:02:50  0:01:48  472k
 61  385M   61  236M    0     0  1409k      0  0:04:39  0:02:51  0:01:48  511k
 61  385M   61  236M    0     0  1405k      0  0:04:40  0:02:52  0:01:48  539k
 61  385M   61  237M    0     0  1400k      0  0:04:41  0:02:53  0:01:48  564k
 61  385M   61  238M    0     0  1396k      0  0:04:42  0:02:54  0:01:48  598k
 61  385M   61  238M    0     0  1391k      0  0:04:43  0:02:55  0:01:48  609k
 62  385M   62  239M    0     0  1387k      0  0:04:44  0:02:56  0:01:48  639k
 62  385M   62  240M    0     0  1384k      0  0:04:45  0:02:57  0:01:48  659k
 62  385M   62  240M    0     0  1380k      0  0:04:45  0:02:58  0:01:47  683k
 62  385M   62  241M    0     0  1377k      0  0:04:46  0:02:59  0:01:47  715k
 62  385M   62  242M    0     0  1373k      0  0:04:47  0:03:00  0:01:47  738k
 63  385M   63  242M    0     0  1369k      0  0:04:48  0:03:01  0:01:47  730k
 63  385M   63  243M    0     0  1366k      0  0:04:48  0:03:02  0:01:46  732k
 63  385M   63  244M    0     0  1361k      0  0:04:49  0:03:03  0:01:46  695k
 63  385M   63  244M    0     0  1356k      0  0:04:50  0:03:04  0:01:46  630k
 63  385M   63  244M    0     0  1351k      0  0:04:51  0:03:05  0:01:46  552k
 63  385M   63  245M    0     0  1345k      0  0:04:53  0:03:06  0:01:47  467k
 63  385M   63  245M    0     0  1338k      0  0:04:54  0:03:07  0:01:47  360k
 63  385M   63  245M    0     0  1332k      0  0:04:56  0:03:08  0:01:48  255k
 63  385M   63  245M    0     0  1326k      0  0:04:57  0:03:09  0:01:48  188k
 63  385M   63  245M    0     0  1316k      0  0:04:59  0:03:10  0:01:49  121k
 63  385M   63  245M    0     0  1311k      0  0:05:00  0:03:11  0:01:49 75650
 63  385M   63  245M    0     0  1305k      0  0:05:02  0:03:12  0:01:50 47716
 63  385M   63  245M    0     0  1299k      0  0:05:03  0:03:13  0:01:50 60285
 63  385M   63  245M    0     0  1288k      0  0:05:06  0:03:15  0:01:51 47602
 63  385M   63  245M    0     0  1281k      0  0:05:07  0:03:16  0:01:51 44526
 63  385M   63  245M    0     0  1279k      0  0:05:08  0:03:16  0:01:52 46642
 63  385M   63  245M    0     0  1273k      0  0:05:09  0:03:17  0:01:52 46344
 63  385M   63  245M    0     0  1268k      0  0:05:11  0:03:18  0:01:53 43105
 63  385M   63  246M    0     0  1262k      0  0:05:12  0:03:19  0:01:53 87198
 63  385M   63  246M    0     0  1258k      0  0:05:13  0:03:20  0:01:53  156k
 64  385M   64  246M    0     0  1254k      0  0:05:14  0:03:21  0:01:53  232k
 64  385M   64  247M    0     0  1252k      0  0:05:14  0:03:22  0:01:52  405k
 64  385M   64  248M    0     0  1250k      0  0:05:15  0:03:23  0:01:52  572k
 64  385M   64  249M    0     0  1246k      0  0:05:16  0:03:24  0:01:52  600k
 64  385M   64  249M    0     0  1241k      0  0:05:17  0:03:25  0:01:52  574k
 64  385M   64  249M    0     0  1236k      0  0:05:19  0:03:26  0:01:53  522k
 64  385M   64  249M    0     0  1231k      0  0:05:20  0:03:27  0:01:53  394k
 64  385M   64  250M    0     0  1227k      0  0:05:21  0:03:28  0:01:53  264k
 65  385M   65  250M    0     0  1223k      0  0:05:22  0:03:29  0:01:53  293k
 65  385M   65  250M    0     0  1220k      0  0:05:23  0:03:30  0:01:53  355k
 65  385M   65  251M    0     0  1217k      0  0:05:23  0:03:31  0:01:52  439k
 65  385M   65  252M    0     0  1217k      0  0:05:24  0:03:32  0:01:52  601k
 66  385M   66  254M    0     0  1219k      0  0:05:23  0:03:33  0:01:50  869k
 66  385M   66  255M    0     0  1220k      0  0:05:23  0:03:34  0:01:49 1063k
 66  385M   66  256M    0     0  1216k      0  0:05:24  0:03:35  0:01:49 1061k
 66  385M   66  256M    0     0  1210k      0  0:05:26  0:03:36  0:01:50  910k
 66  385M   66  256M    0     0  1206k      0  0:05:26  0:03:37  0:01:49  769k
 66  385M   66  256M    0     0  1202k      0  0:05:28  0:03:38  0:01:50  463k
 66  385M   66  256M    0     0  1197k      0  0:05:29  0:03:39  0:01:50  218k
 66  385M   66  257M    0     0  1194k      0  0:05:30  0:03:40  0:01:50  207k
 66  385M   66  257M    0     0  1191k      0  0:05:31  0:03:41  0:01:50  317k
 67  385M   67  258M    0     0  1190k      0  0:05:31  0:03:42  0:01:49  482k
 67  385M   67  260M    0     0  1192k      0  0:05:30  0:03:43  0:01:47  778k
 68  385M   68  262M    0     0  1199k      0  0:05:29  0:03:44  0:01:45 1267k
 69  385M   69  267M    0     0  1212k      0  0:05:25  0:03:45  0:01:40 2036k
 71  385M   71  273M    0     0  1236k      0  0:05:19  0:03:46  0:01:33 3243k
 72  385M   72  280M    0     0  1260k      0  0:05:12  0:03:47  0:01:25 4383k
 73  385M   73  284M    0     0  1276k      0  0:05:09  0:03:48  0:01:21 5040k
 74  385M   74  288M    0     0  1288k      0  0:05:06  0:03:49  0:01:17 5314k
 76  385M   76  292M    0     0  1300k      0  0:05:03  0:03:50  0:01:13 5278k
 76  385M   76  296M    0     0  1309k      0  0:05:01  0:03:51  0:01:10 4606k
 77  385M   77  299M    0     0  1317k      0  0:04:59  0:03:52  0:01:07 3914k
 78  385M   78  302M    0     0  1327k      0  0:04:57  0:03:53  0:01:04 3640k
 79  385M   79  306M    0     0  1337k      0  0:04:55  0:03:54  0:01:01 3551k
 80  385M   80  309M    0     0  1346k      0  0:04:53  0:03:55  0:00:58 3451k
 80  385M   80  311M    0     0  1348k      0  0:04:52  0:03:56  0:00:56 3134k
 80  385M   80  311M    0     0  1342k      0  0:04:53  0:03:57  0:00:56 2463k
 80  385M   80  311M    0     0  1336k      0  0:04:55  0:03:59  0:00:56 1713k
 80  385M   80  311M    0     0  1332k      0  0:04:56  0:03:59  0:00:57 1133k
 80  385M   80  312M    0     0  1328k      0  0:04:57  0:04:00  0:00:57  465k
 81  385M   81  312M    0     0  1324k      0  0:04:57  0:04:01  0:00:56  171k
 81  385M   81  312M    0     0  1320k      0  0:04:58  0:04:02  0:00:56  229k
 81  385M   81  313M    0     0  1319k      0  0:04:59  0:04:03  0:00:56  423k
 81  385M   81  315M    0     0  1319k      0  0:04:59  0:04:04  0:00:55  676k
 82  385M   82  317M    0     0  1323k      0  0:04:58  0:04:05  0:00:53 1088k
 83  385M   83  320M    0     0  1332k      0  0:04:56  0:04:06  0:00:50 1757k
 84  385M   84  326M    0     0  1350k      0  0:04:52  0:04:07  0:00:45 2814k
 85  385M   85  330M    0     0  1362k      0  0:04:49  0:04:08  0:00:41 3505k
 86  385M   86  333M    0     0  1369k      0  0:04:48  0:04:09  0:00:39 3819k

In [6]:
!pip install pymorphy3

from pymorphy3 import MorphAnalyzer

Requirement already satisfied: pymorphy3 in c:\users\professional\appdata\local\programs\python\python311\lib\site-packages (2.0.6)
Requirement already satisfied: dawg2-python>=0.8.0 in c:\users\professional\appdata\local\programs\python\python311\lib\site-packages (from pymorphy3) (0.9.0)
Requirement already satisfied: pymorphy3-dicts-ru in c:\users\professional\appdata\local\programs\python\python311\lib\site-packages (from pymorphy3) (2.4.417150.4580142)

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import re
import gensim
import logging
import nltk.data
import pandas as pd
import urllib.request
from bs4 import BeautifulSoup
from nltk.corpus import stopwords
from gensim.models import word2vec
from nltk.tokenize import sent_tokenize, RegexpTokenizer
from pymorphy2 import MorphAnalyzer
from gensim.test.utils import datapath
nltk.download('punkt')

from nltk import FreqDist
from tqdm import tqdm_notebook as tqdm
from sklearn.manifold import TSNE

from bokeh.models import ColumnDataSource, LabelSet
from bokeh.plotting import figure, show, output_file
from bokeh.io import output_notebook

from sklearn.decomposition import TruncatedSVD
import fasttext

from functools import lru_cache
from multiprocessing import Pool
import numpy as np
from sklearn.model_selection import train_test_split
from tqdm import tqdm_notebook as tqdm
import re

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Professional\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [5]:
model_path = 'ruwikiruscorpora-nobigrams_upos_skipgram_300_5_2018.vec.gz'

model_ru = gensim.models.KeyedVectors.load_word2vec_format(model_path, binary=False)

Take a few words for example:

In [4]:
words = ['день_NOUN', 'ночь_NOUN', 'человек_NOUN', 'семантика_NOUN', 'биткоин_NOUN']

Frequency tags are needed, since it is the specifics of the downloaded model - it was trained in words announced by their parts of speech (and lemmetized). ** NB! ** The names of models on `rusvectores` indicate which tigset they use (Mystem, Upos, etc.)

Let us ask the model 10 closest neighbors for each word and the coefficient of cosine proximity to everyone:

In [5]:
for word in words:
    # есть ли слово в модели?
    if word in model_ru:
        print(word)
        # смотрим на вектор слова (его размерность 300, смотрим на первые 10 чисел)
        print(model_ru[word][:10])
        # выдаем 10 ближайших соседей слова:
        for word, sim in model_ru.most_similar(positive=[word], topn=10):
            # слово + коэффициент косинусной близости
            print(word, ': ', sim)
        print('\n')
    else:
        # Увы!
        print('Увы, слова "%s" нет в модели!' % word)

день_NOUN
[ 0.117177  0.008562 -0.054731  0.03821   0.006885  0.041716  0.063708
  0.070478  0.032087  0.050791]
неделя_NOUN :  0.7242119312286377
месяц_NOUN :  0.7178640365600586
утро_NOUN :  0.6738513708114624
вечер_NOUN :  0.6443344950675964
воскресенье_NOUN :  0.6362559795379639
час_NOUN :  0.632983386516571
накануне_ADV :  0.6304810047149658
днями_NOUN :  0.6276212930679321
днемя_NOUN :  0.621060848236084
ночь_NOUN :  0.6077756285667419


ночь_NOUN
[ 0.070529 -0.068594  0.029781  0.035559 -0.01488   0.072418 -0.01183
  0.051797 -0.024269  0.034406]
ночь_PROPN :  0.7884491682052612
вечер_NOUN :  0.7778281569480896
утро_NOUN :  0.7638111710548401
полночь_NOUN :  0.7437741756439209
рассвет_NOUN :  0.6889956593513489
полдень_NOUN :  0.6811894178390503
утро_PROPN :  0.6788180470466614
сумерки_NOUN :  0.6461666822433472
напроать_NOUN :  0.6451945900917053
напролет_VERB :  0.6393611431121826


человек_NOUN
[ 0.022094 -0.077399  0.038363 -0.051602  0.000347  0.073115 -0.068763
 -0.037081 -0.057053  0.103592]
человеколо_NOUN :  0.6339133381843567
людямя_NOUN :  0.5752431154251099
человек_PROPN :  0.562440037727356
людей_NOUN :  0.5577748417854309
плотностьнаселение_PROPN :  0.5463516116142273
человекомя_NOUN :  0.541978120803833
микрочел/кв.етр_NOUN :  0.5279955267906189
человека_NOUN :  0.5220513939857483
,человек_ADJ :  0.5200932621955872
душа_NOUN :  0.5174600481987


семантика_NOUN
[ 0.145827  0.079547 -0.015398  0.044673  0.01098   0.018703 -0.017285
 -0.003601 -0.012524 -0.03982 ]
семантический_ADJ :  0.7788299918174744
синтаксический_ADJ :  0.7409731149673462
-семантический_ADJ :  0.7346712946891785
метаязык_NOUN :  0.7314320206642151
синтаксис_NOUN :  0.7253472208976746
семантико_ADJ :  0.723125159740448
семантика_PROPN :  0.7222791314125061
парадигматика_NOUN :  0.7084903717041016
синтактика_NOUN :  0.7036083340644836
интенсиональный_ADJ :  0.7011395692825317


Увы, слова "биткоин_NOUN" нет в модели!

We find the cosine closeness of a pair of words:

In [6]:
print(model_ru.similarity('nvidia_PROPN', 'видеокарта_NOUN'))

0.7847429

What happens if you subtract Italy from pizza and add Siberia?

* Positive - vectors that we add
* Negative - vectors that we subtract

In [7]:
print(model_ru.most_similar(positive=['татарин_NOUN', 'казахстан_NOUN'], negative=['казах_NOUN'])[0][0])

татарстан_NOUN

In [8]:
model_ru.doesnt_match('бешбармак_NOUN плов_NOUN манты_NOUN'.split())

'манты_NOUN'

** Warm exercises **

Find an example of a multi-valued word for which in the top 10 (method `most_similar`) words similar to it include words related to different meanings:

In [9]:
model_ru.most_similar(positive=['кисть_NOUN'], topn=10)

[('кисть_VERB', 0.6543477177619934),
 ('кисть_PROPN', 0.6166998147964478),
 ('кисти_NOUN', 0.6121705770492554),
 ('кистевой_ADJ', 0.5860570073127747),
 ('палец_NOUN', 0.5834868550300598),
 ('кисточка_NOUN', 0.5757529735565186),
 ('запястие_NOUN', 0.5751310586929321),
 ('запястье_NOUN', 0.5745604038238525),
 ('мазок_NOUN', 0.5602888464927673),
 ('щетинный_ADJ', 0.5586758255958557)]

In [10]:
model_ru.most_similar(positive=['ручка_NOUN'], topn=10)

[('рукоятка_NOUN', 0.6724830269813538),
 ('рычажка_NOUN', 0.6518499851226807),
 ('отвертку_NOUN', 0.6511660218238831),
 ('рычажок_NOUN', 0.6296215653419495),
 ('подставочка_NOUN', 0.6216707825660706),
 ('плечико_NOUN', 0.6195791959762573),
 ('пилочка_NOUN', 0.6192642450332642),
 ('валика_NOUN', 0.6162146329879761),
 ('пальчик_NOUN', 0.614273190498352),
 ('ручонка_NOUN', 0.605606198310852)]

By analogy with Italy - pizza, Siberia - cracker, come up with a similar bunch of words for verification:

In [11]:
model_ru.most_similar(positive=['япония_NOUN'], negative=['суши_NOUN'])

[('япония_PROPN', 0.3335132598876953),
 ('коток_PROPN', 0.3177908957004547),
 ('японии_NOUN', 0.3012892007827759),
 ('тэнный_ADV', 0.28885895013809204),
 ('тосимити_PROPN', 0.28035661578178406),
 ('гмд_PROPN', 0.27687060832977295),
 ('акао_PROPN', 0.2763778567314148),
 ('ёсихито_PROPN', 0.2689056992530823),
 ('хасимото_PROPN', 0.2671535611152649),
 ('томио_PROPN', 0.2645207643508911)]

In [12]:
model_ru.most_similar(positive=['корова_NOUN', 'мёд_NOUN'], negative=['пчела_NOUN'])

[('коровы_NOUN', 0.5042323470115662),
 ('молоко_NOUN', 0.5000815987586975),
 ('коровий_NOUN', 0.49488502740859985),
 ('буренка_NOUN', 0.48815253376960754),
 ('овца_NOUN', 0.48311418294906616),
 ('коров_NOUN', 0.48277124762535095),
 ('овец_NOUN', 0.4806281626224518),
 ('молоко_ADV', 0.4783443808555603),
 ('нетель_NOUN', 0.47492921352386475),
 ('теленок_NOUN', 0.47437888383865356)]

Give an example of three words W1, W2, W3, such that W1 and W2 are synonyms, W1 and W3 are antonyms, but at the same time, Similarity (W1, W2) <Similarity (W1, W3).

In [13]:
model_ru.most_similar(positive=['сильный_ADJ'], topn=10)

[('слабый_ADJ', 0.6777516603469849),
 ('мощный_ADJ', 0.6326162815093994),
 ('сильно_ADJ', 0.6270166635513306),
 ('сильнейший_ADJ', 0.6017962098121643),
 ('усиливаться_VERB', 0.5654467344284058),
 ('крепкий_ADJ', 0.5633267760276794),
 ('несильный_ADJ', 0.5593032836914062),
 ('сильный_ADV', 0.5490185618400574),
 ('могучий_ADJ', 0.5273253321647644),
 ('стремителный_ADJ', 0.5216044783592224)]

In [14]:
print(model_ru.similarity('сильный_ADJ', 'мощный_ADJ'))
print(model_ru.similarity('сильный_ADJ', 'слабый_ADJ'))

0.63261634
0.6777517

### Exercise

Write a function that accepts the proposal to the input, and replaces the random noun in it with Associat - the closest word to it from the Word2VEC model.

NB: For this you will need a morphological analyzer. I advise you to use Pymorphy (we briefly talked about it at the last seminar).

How to use Pymorphy:

In [15]:
from pymorphy3 import MorphAnalyzer

analyser = MorphAnalyzer()

In [16]:
# разобрать слово (в данном случае возможно два разбора, поэтому получаем список из двух элементов)
result = analyser.parse('слово')
result

[Parse(word='слово', tag=OpencorporaTag('NOUN,inan,neut sing,nomn'), normal_form='слово', score=0.59813, methods_stack=((DictionaryAnalyzer(), 'слово', 54, 0),)),
 Parse(word='слово', tag=OpencorporaTag('NOUN,inan,neut sing,accs'), normal_form='слово', score=0.401869, methods_stack=((DictionaryAnalyzer(), 'слово', 54, 3),))]

In [17]:
# достать часть речи
result[0].tag.POS

'NOUN'

In [18]:
# поставить в дательный падеж
result[0].inflect(frozenset(['datv'])).word

'слову'

Your function (for simplicity, you can not try to put the word in the "necessary" form and limit yourself to a nominative case):

In [19]:
model_ru.most_similar(positive=['купить_VERB'], topn=1)

[('покупать_VERB', 0.8457080125808716)]

In [20]:
sent = 'маленький_ADJ человек_NOUN увидеть_VERB обезьяна_NOUN италия_NOUN'.split()
new_sent = ''
for word in sent:
    # word = word.lower()
    result = analyser.parse(word)[0].tag.POS
    new_word = f'{word}_{result}'
    top1 = model_ru.most_similar(positive=[word], topn=1)[0][0].split('_')[0]
    new_sent += top1 + ' '
new_sent

'крошечный человеколо видеть обезьяна франция '

In [21]:
import random

def change_random_noun(sentence, model):
    morph = analyser
    words = sentence.split()
    
    nouns = [w for w in words if morph.parse(w)[0].tag.POS == 'NOUN']
    
    if not nouns:
        return sentence  
    
    target = random.choice(nouns)
    
    parsed = morph.parse(target)[0]
    lemma = parsed.normal_form + "_NOUN"
    
    if lemma not in model:
        return sentence  
    
  
    similar = model.most_similar(lemma, topn=10)
    
    for word, score in similar:
        new_word = word.split('_')[0]
        if new_word != parsed.normal_form:
            replacement = new_word
            break
    else:
        return sentence  
    
    if target[0].isupper():
        replacement = replacement.capitalize()
    
    # replace in sentence
    new_sentence = [replacement if w == target else w for w in words]
    return ' '.join(new_sentence)

In [22]:
sent = 'Ученик идёт в школу'
print(change_random_noun(sent, model_ru))

Ученица идёт в школу

## how to train your model

As training data, we take the marked and unreasonable reviews about films (the dataset is taken with Kaggle).

In [23]:
data = pd.read_csv("unlabeledTrainData.tsv", header=0, delimiter="\t", quoting=3)

len(data)

50000

In [24]:
data.head()

          id                                             review
0   "9999_0"  "Watching Time Chasers, it obvious that it was...
1  "45057_0"  "I saw this film about 20 years ago and rememb...
2  "15561_0"  "Minor Spoilers<br /><br />In New York, Joan B...
3   "7161_0"  "I went to see this film with a great deal of ...
4  "43971_0"  "Yes, I agree with everyone on this site this ...

We remove the link from the data, the HTML damping and non-table symbols, and then bring everything to the lower register and tocenize. The output is an array of sentences, each of which is an array of words. A tokenizer from the `nltk` library is used here.

In [25]:
from nltk.tokenize import PunktSentenceTokenizer
tokenizer = PunktSentenceTokenizer()
sentences = tokenizer.tokenize("This is a test. Here is another sentence.")

In [26]:
def review_to_wordlist(review, remove_stopwords=False ):
    # убираем ссылки
    review = re.sub(r"http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+", " ", review)
    # достаем сам текст
    review_text = BeautifulSoup(review, "lxml").get_text()
    # оставляем только буквенные символы
    review_text = re.sub("[^a-zA-Z]"," ", review_text)
    # приводим к нижнему регистру и разбиваем на слова по символу пробела
    words = review_text.lower().split()
    if remove_stopwords: # убираем стоп-слова
        stops = stopwords.words("english")
        words = [w for w in words if not w in stops]
    return(words)

def review_to_sentences(review, tokenizer, remove_stopwords=False):
    # разбиваем обзор на предложения
    raw_sentences = tokenizer.tokenize(review.strip())
    sentences = []
    # применяем предыдущую функцию к каждому предложению
    for raw_sentence in raw_sentences:
        if len(raw_sentence) > 0:
            sentences.append(review_to_wordlist(raw_sentence, remove_stopwords))
    return sentences

In [27]:
#logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

sentences = []

print("Parsing sentences from training set...")
for review in data["review"]:
    sentences += review_to_sentences(review, tokenizer)

Parsing sentences from training set...

C:\Users\Professional\AppData\Local\Temp\ipykernel_15456\3276744398.py:5: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  review_text = BeautifulSoup(review, "lxml").get_text()

In [28]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Professional\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [29]:
print(len(sentences))
print(sentences[0])

533357
['watching', 'time', 'chasers', 'it', 'obvious', 'that', 'it', 'was', 'made', 'by', 'a', 'bunch', 'of', 'friends']

In [71]:
# это понадобится нам позже

with open('clean_text.txt', 'w') as f:
    for s in sentences[:5000]:
        f.write(' '.join(s))
        f.write('\n')

We teach and save the model.


Main parameters:
* Data must be an iterized object
* Size - size vector,
* Window - observation window size,
* min_count - min. The frequency of the word in the case,
* SG-used learning algorithm (0-CBOW, 1-SKIP-GRAM),
* sample - threshold for download of high -frequency words,
* works - the number of flows,
* alpha — learning rate,
* Iter - the number of iterations,
* max_vocab_size - allows you to set the restriction from memory when creating a dictionary (i.e., if the restriction is exceeded, then low -frequency words will be released). For comparison: 10 million words = 1GB RAM.

** NB! ** Please note that the modeling of the model does not include preprocessing! This means that getting rid of punctuation, leading words to the lower register, lemmetizing them, and frequency tags will have to be affixed before modeling the model (unless, of course, this is necessary for your task). Those. In what form the words will be in the original text, in this they will be in the model.

In [31]:
print("Training model...")

%time model_en = word2vec.Word2Vec(sentences, workers=4, vector_size=300, min_count=10, window=10, sample=1e-3)

Training model...
CPU times: total: 3min 23s
Wall time: 54.9 s

We look how many words are in the model.

In [32]:
print(len(model_en.wv.key_to_index))

28308

Let's try to evaluate the model manually by solving examples. A little given below, try to come up with your own.

In [33]:
print(model_en.wv.most_similar(positive=["king", "woman"], negative=["man"], topn=3))
print(model_en.wv.most_similar(positive=["dogs", "man"], negative=["dog"], topn=1))

print(model_en.wv.most_similar("usa", topn=3))

print(model_en.wv.doesnt_match("comedy thriller western novel".split()))

[('princess', 0.5691617131233215), ('queen', 0.55782550573349), ('prince', 0.536369800567627)]
[('men', 0.6445133686065674)]
[('europe', 0.7251085042953491), ('germany', 0.7144233584403992), ('north', 0.7128341794013977)]
novel

### How to receive an existing model

When training, the “weight” models are initialized by accident, but it can be used to initialize weight vectors from a pre -scientific model, thus, as it were, who is accustomed to it.

First, let's see the proximity of some pair of words in the existing model, then to compare the result with the learned one.

In [34]:
model_en.wv.similarity('italy', 'north')

0.67672956

As additional data for learning, take the English text “Alice in the Zadaker”.

In [35]:
with open("alice.txt", 'r', encoding='utf-8') as f:
    text = f.read()

# убираем переносы строк, токенизируем текст
text = re.sub('\n', ' ', text)
tokenizer = PunktSentenceTokenizer()
sents = tokenizer.tokenize(text)

# убираем всю пунктуацию и делим текст на слова по пробелу
punct = '!"#$%&()*+,-./:;<=>?@[\]^_`{|}~„“«»†*—/\-‘’'
clean_sents = []
for sent in sents:
    s = [w.lower().strip(punct) for w in sent.split()]
    clean_sents.append(s)

print(clean_sents[:2])

[['through', 'the', 'looking-glass', 'by', 'lewis', 'carroll', 'chapter', 'i', 'looking-glass', 'house', 'one', 'thing', 'was', 'certain', 'that', 'the', 'white', 'kitten', 'had', 'had', 'nothing', 'to', 'do', 'with', 'it', '', 'it', 'was', 'the', 'black', 'kitten’s', 'fault', 'entirely'], ['for', 'the', 'white', 'kitten', 'had', 'been', 'having', 'its', 'face', 'washed', 'by', 'the', 'old', 'cat', 'for', 'the', 'last', 'quarter', 'of', 'an', 'hour', 'and', 'bearing', 'it', 'pretty', 'well', 'considering', 'so', 'you', 'see', 'that', 'it', 'couldn’t', 'have', 'had', 'any', 'hand', 'in', 'the', 'mischief']]

To receive the model, you must first save it, and then load it. All parameters of the training (the size of the vector, min. The frequency of the word, etc.) will be taken from the loaded model, i.e. You can’t again set them.

** NB! ** You can only receive a full model, and `keyedVectors` is impossible. Therefore, the model must be preserved in a corresponding format. Read more about the difference XX_MarkDown_Link_XX.

In [36]:
model_path = "movie_reviews.model"

print("Saving model...")
model_en.save(model_path)

Saving model...

In [37]:
model = word2vec.Word2Vec.load(model_path)

model.build_vocab(clean_sents, update=True)
model.train(clean_sents, total_examples=model.corpus_count, epochs=5)

(96842, 150225)

Leo and rabbit have become closer to each other!

In [38]:
model.wv.similarity('lion', 'cat')

0.3021703

You can normalize the vector, then the model will occupy less RAM. However, after that it cannot be finished. Here, L2-Normalization is used: the vectors are normalized so that if you fold the squares of all elements of the vector, in total it turns out 1.

In addition, we will preserve not complete vectors, but `KeyedVectors`.

In [39]:
# model.init_sims(replace=True)
model_path = "movies_alice.bin"

print("Saving model...")
model.wv.save_word2vec_format(model_path, binary=True)

Saving model...

## assessment

This, of course, is good, but how to understand which model is better? Or, for example, I made my model, but how to understand how good it is?

For this, there are special datasets to assess the quality of distribution models. The main two: one measures the accuracy of solving problems on analogy (about Russia and dumplings), and the second is used to assess the coefficient of semantic proximity.

### Word Similarity

This method is to evaluate how ideas about the semantic proximity of words in the model are related to the "ideas" of people.

| Word 1 | Word 2 | proximity |
|------------|------------|----------|
| cat | dog | 0.7 |
| Cup | mug | 0.9 |

For each pair of words from a predetermined dataset, we can calculate the cosine distance, and get a list of such meanings. At the same time, we already have a list of meanings made by people. We can compare these two lists and understand how similar they are (for example, considering the correlation). This measure of similarity should talk about how well the model simulates the distance to the word.

### analogies

Another popular task for an “internal” assessment is called the task of searching analogies. As we have already analyzed above, with the help of simple arithmetic operations, we can modify the meaning of the word. If you collect a set of words-modifiers in advance, as well as the words that we want to get into the results of the modification, then based on the calculation of the number of “hits” in the desired word, we can evaluate how well the model works well.

As a word-modifier, we can use semantic analogies. Say, if we have some attitude of the "country country", then to evaluate the model we can use pairs like "Russia-Moscow", "Norway-Ovos", etc. Dataset will look as follows:

| Word 1 | Word 2 | Attitude
|------------|------------|---------------|
| Russia | Moscow | Country Country |
| Norway | Oslo Side

Considering the random two pairs from this set, we want to, having a triplet (Russia, Moscow, Norway), we want to get the word "Oslo", i.e. Find the word that will be in the same respect with the word "Norway" as "Russia" is with Moscow.

Datasets for the Russian language can be downloaded on a page with models on rusvectores. We calculate the quality of our NKRA model on the Dataset about the analogy:

In [40]:
! curl -L -o questions-words.txt https://raw.githubusercontent.com/RaRe-Technologies/gensim/develop/gensim/test/test_data/questions-words.txt
file_txt = open('questions-words.txt', 'r')
file_txt.readline()

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  589k  100  589k    0     0   567k      0  0:00:01  0:00:01 --:--:--  568k

': capital-common-countries\n'

In [41]:
res = model.wv.evaluate_word_analogies(datapath('questions-words.txt'))

In [42]:
res[0]

0.24410401128804676

## visualization

You can see the resulting model by visualizing it, for example, on a plane.
### T-Sne

** T-SNE ** (*t-distributed stochastic neighbor embedding*)-a technique of non-linear decrease in dimension and visualization of multidimensional variables. It is designed specifically for the high dimension data L. van der Maaten and D. Hinton, XX_MarkDown_Link_XX. T-SNE is an iterative algorithm based on the calculation of pair distances between all objects (including therefore, it is quite slow).


We portray on a plane of 1000 most frequency words from a collection of texts about cinema:

In [43]:
top_words = []


fd = FreqDist()
for s in tqdm(sentences):
    fd.update(s)

for w in fd.most_common(1000):
    top_words.append(w[0])

print(top_words[:50:])
top_words_vec = model.wv[top_words]

C:\Users\Professional\AppData\Local\Temp\ipykernel_15456\2085447832.py:5: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for s in tqdm(sentences):

  0%|          | 0/533357 [00:00<?, ?it/s]

['the', 'and', 'a', 'of', 'to', 'is', 'it', 'in', 'i', 'this', 'that', 's', 'was', 'as', 'with', 'for', 'movie', 'but', 'film', 'you', 't', 'on', 'not', 'he', 'are', 'his', 'have', 'be', 'one', 'all', 'they', 'at', 'by', 'who', 'an', 'from', 'so', 'like', 'there', 'or', 'her', 'just', 'about', 'out', 'has', 'if', 'what', 'some', 'good', 'can']

In [44]:
top_words_vec = model.wv[top_words]
print(top_words_vec)

[[ 1.1152246e-02 -1.5347273e+00  7.3800260e-01 ... -1.3592858e-02
  -3.1594300e-01  8.8506693e-01]
 [ 2.9659975e-01 -1.1017758e+00  7.9434407e-01 ... -2.3897734e-01
  -8.9180022e-01  1.0113499e+00]
 [ 1.2098911e+00 -1.6420239e+00  1.6188014e+00 ... -5.4604304e-01
   3.0194479e-01 -2.1609092e-01]
 ...
 [-6.5389931e-01 -8.9825785e-01 -1.4328576e+00 ...  1.3868723e+00
   5.1971883e-01  1.5025042e+00]
 [ 4.7558135e-01  4.9205136e-01 -8.6904341e-01 ... -7.1809864e-01
   1.9389552e-01 -9.8982364e-01]
 [ 6.5164977e-01 -3.7113747e-01  9.4442981e-01 ... -1.8939815e-01
  -1.3576854e-03  6.3961184e-01]]

In [50]:
!pip install --upgrade numpy scikit-learn threadpoolctl

Requirement already satisfied: numpy in c:\users\professional\appdata\local\programs\python\python311\lib\site-packages (1.26.4)
Collecting numpy
  Using cached numpy-2.3.3-cp311-cp311-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: scikit-learn in c:\users\professional\appdata\local\programs\python\python311\lib\site-packages (1.7.2)
Requirement already satisfied: threadpoolctl in c:\users\professional\appdata\local\programs\python\python311\lib\site-packages (3.6.0)
Requirement already satisfied: scipy>=1.8.0 in c:\users\professional\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.12.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\professional\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.4.0)

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [51]:
!pip install openTSNE

Requirement already satisfied: openTSNE in c:\users\professional\appdata\local\programs\python\python311\lib\site-packages (1.0.2)
Requirement already satisfied: numpy>=1.16.6 in c:\users\professional\appdata\local\programs\python\python311\lib\site-packages (from openTSNE) (1.26.4)
Requirement already satisfied: scikit-learn>=0.20 in c:\users\professional\appdata\local\programs\python\python311\lib\site-packages (from openTSNE) (1.7.2)
Requirement already satisfied: scipy in c:\users\professional\appdata\local\programs\python\python311\lib\site-packages (from openTSNE) (1.12.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\professional\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn>=0.20->openTSNE) (1.4.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\professional\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn>=0.20->openTSNE) (3.6.0)

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [45]:
from openTSNE import TSNE

In [51]:
%%time
tsne = TSNE(n_components=2, random_state=0)

CPU times: total: 21.5 s
Wall time: 21.6 s

In [ ]:
!conda install -c conda-forge scikit-learn

In [50]:
top_words_tsne = tsne.fit(top_words_vec)

In [52]:
output_notebook()

p = figure(tools="pan,wheel_zoom,reset,save",
           toolbar_location="above",
           title="word2vec T-SNE (eng model, top1000 words)")

source = ColumnDataSource(data=dict(x1=top_words_tsne[:,0],
                                    x2=top_words_tsne[:,1],
                                    names=top_words))

p.scatter(x="x1", y="x2", size=8, source=source)

labels = LabelSet(x="x1", y="x2", text="names", y_offset=6,
                  text_font_size="8pt", text_color="#555555",
                  source=source, text_align='center')
p.add_layout(labels)

show(p)

To calculate the transformation of T-SNE faster (and sometimes more effective), you can first reduce the dimension of the source data using, for example, SVD, and then use T-SNE:

In [56]:
svd_50 = TruncatedSVD(n_components=50)
top_words_vec_50 = svd_50.fit_transform(top_words_vec)
top_words_tsne2 = TSNE(n_components=2, random_state=0).fit(top_words_vec_50)

In [57]:
output_notebook()

p = figure(tools="pan,wheel_zoom,reset,save",
           toolbar_location="above",
           title="word2vec T-SNE (eng model, top1000 words, +SVD)")

source = ColumnDataSource(data=dict(x1=top_words_tsne2[:,0],
                                    x2=top_words_tsne2[:,1],
                                    names=top_words))

p.scatter(x="x1", y="x2", size=8, source=source)

labels = LabelSet(x="x1", y="x2", text="names", y_offset=6,
                  text_font_size="8pt", text_color="#555555",
                  source=source, text_align='center')
p.add_layout(labels)

show(p)

## fastxt

FastText uses not only words embeldings, but also n-grams. In the case, each word is automatically represented in the form of a set of symbolic N-grams. Say, if we set n = 3, then the vector for the word "What" will be represented by the sum of the vectors of the following trigrams: "<when", "whe", "her", "er", "re>" (where "<" and ">" symbols indicating the beginning of the word). Thanks to this, we can also receive vectors for words that are absent in the dictionary, as well as work effectively with texts containing errors and typos.

* [Статья](https://aclweb.org/anthology/Q17-1010)
* [Сайт](https://fasttext.cc/)
* [Тьюториал](https://fasttext.cc/docs/en/support.html)
* [Вектора для 157 языков](https://fasttext.cc/docs/en/crawl-vectors.html)
* [Вектора, обученные на википедии](https://fasttext.cc/docs/en/pretrained-vectors.html) (separately for 294 different languages)
* [Репозиторий](https://github.com/facebookresearch/fasttext)

There is a library `FastText` for python (with ready -made models you can work through` Gensim`).

In [72]:
# так можно обучить свою модель
ft_model = fasttext.train_unsupervised('clean_text.txt', minn=3, maxn=4, dim=300)

In [73]:
ft_model.get_word_vector("movie")[:20]

array([-0.00416676,  0.05092802, -0.08223595, -0.09361413,  0.04414225,
       -0.09659433,  0.06567546, -0.06228702,  0.05990359,  0.10483559,
       -0.02215734,  0.03157882,  0.22056833,  0.02658796, -0.06879877,
       -0.04878161,  0.01972723, -0.09090523,  0.09340917,  0.13541059],
      dtype=float32)

In [74]:
ft_model.get_nearest_neighbors('queen')

[(0.9998556971549988, 'between'),
 (0.9998512268066406, 'green'),
 (0.9997908473014832, 'halloween'),
 (0.9997682571411133, 'teen'),
 (0.9997453093528748, 'screen'),
 (0.9997159838676453, 'golden'),
 (0.9997013807296753, 'spoken'),
 (0.9996824860572815, 'ten'),
 (0.9996806383132935, 'hayden'),
 (0.9996733665466309, 'listen')]

In [75]:
ft_model.get_analogies("woman", "man", "actor")

[(0.9994927644729614, 'absolutely'),
 (0.999439001083374, 'sadly'),
 (0.999413251876831, 'badly'),
 (0.9994124174118042, 'bad'),
 (0.9994093179702759, 'actually'),
 (0.9993826746940613, 'subtly'),
 (0.9993740320205688, 'exactly'),
 (0.9993736147880554, 'simply'),
 (0.9993654489517212, 'recently'),
 (0.9993556141853333, 'fly')]

In [69]:
# проблема с опечатками решена

ft_model.get_nearest_neighbors('actr')

[(0.9997531771659851, 'act'),
 (0.9995146989822388, 'actors'),
 (0.9994714260101318, 'actress'),
 (0.9993541836738586, 'terrible'),
 (0.9993489980697632, 'actor'),
 (0.9993090033531189, 'acted'),
 (0.9993076324462891, 'poorly'),
 (0.999283492565155, 'mostly'),
 (0.9992623329162598, 'exactly'),
 (0.9992544054985046, 'practically')]

In [70]:
# проблема с out of vocabulary словами - тоже

ft_model.get_nearest_neighbors('moviegeek')

[(0.9997233152389526, 'honestly'),
 (0.9997131824493408, 'unlike'),
 (0.9997020959854126, 'thoroughly'),
 (0.9996803402900696, 'move'),
 (0.9996675252914429, 'although'),
 (0.9996499419212341, 'sit'),
 (0.9996488094329834, 'views'),
 (0.9996460676193237, 'honest'),
 (0.9996401071548462, 'realise'),
 (0.9996283054351807, 'watchable')]

In [76]:
! curl -L -o positive.csv https://www.dropbox.com/s/fnpq3z4bcnoktiv/positive.csv?dl=0
! curl -L -o negative.csv https://www.dropbox.com/s/r6u59ljhhjdg6j0/negative.csv?dl=0

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   129  100   129    0     0    205      0 --:--:-- --:--:-- --:--:--   205

  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100    17  100    17    0     0     14      0  0:00:01  0:00:01 --:--:--  8500

  0 25.0M    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  1 25.0M    1  288k    0     0  97559      0  0:04:28  0:00:03  0:04:25  516k
 22 25.0M   22 5663k    0     0  1406k      0  0:00:18  0:00:04  0:00:14 3625k
 64 25.0M   64 16.1M    0     0  3281k      0  0:00:07  0:00:05  0:00:02 6436k
100 25.0M  100 25.0M    0     0  4312k      0  0:00:05  0:00:05 --:--:-- 7372k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   129  100   129    0     0    218      0 --:--:-- --:--:-- --:--:--   219

100    17  100    17    0     0     14      0  0:00:01  0:00:01 --:--:--    14
100    17  100    17    0     0     14      0  0:00:01  0:00:01 --:--:--     0

  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  6 23.3M    6 1551k    0     0   521k      0  0:00:45  0:00:02  0:00:43 1618k
 10 23.3M   10 2575k    0     0   647k      0  0:00:36  0:00:03  0:00:33 1315k
 29 23.3M   29 7087k    0     0  1426k      0  0:00:16  0:00:04  0:00:12 2402k
 66 23.3M   66 15.4M    0     0  2643k      0  0:00:09  0:00:05  0:00:04 3994k
100 23.3M  100 23.3M    0     0  3550k      0  0:00:06  0:00:06 --:--:-- 5073k

In [12]:
positive = pd.read_csv('positive.csv', sep=';', usecols=[3], names=['text'])
positive['label'] = ['positive'] * len(positive)
negative = pd.read_csv('negative.csv', sep=';', usecols=[3], names=['text'])
negative['label'] = ['negative'] * len(negative)
df = pd.concat((positive, negative))
df.head()

                                                text     label
0  @first_timee хоть я и школота, но поверь, у на...  positive
1  Да, все-таки он немного похож на него. Но мой ...  positive
2  RT @KatiaCheh: Ну ты идиотка) я испугалась за ...  positive
3  RT @digger2912: "Кто то в углу сидит и погибае...  positive
4  @irina_dyshkant Вот что значит страшилка :D\nН...  positive

In [13]:
len(df)

226834

We will conduct standard pre -processing:

In [7]:
m = MorphAnalyzer()

regex = re.compile("[А-Яа-я:=!\)\()A-z\_\%/|]+")

def words_only(text, regex=regex):
    try:
        return regex.findall(text)
    except:
        return []

In [8]:
#@lru_cache(maxsize=128)
# если вы работаете не колабе, можно заменить pymorphy на mystem и раскомментирвать первую строку про lru_cache
def lemmatize(text, pymorphy=m):
    try:
        return " ".join([pymorphy.parse(w)[0].normal_form for w in text])
    except:
        return " "

In [9]:
def clean_text(text):
    return lemmatize(words_only(text))

In [10]:
5

5

In [14]:
lemmas = [clean_text(text) for text in tqdm(df['text'], total=len(df))]

df['lemmas'] = lemmas
df.head()

C:\Users\Professional\AppData\Local\Temp\ipykernel_14276\3431646987.py:1: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  lemmas = [clean_text(text) for text in tqdm(df['text'], total=len(df))]

  0%|          | 0/226834 [00:00<?, ?it/s]

,text,label,lemmas
0,"@first_timee хоть я и школота, но поверь, у на...",positive,first_timee хоть я и школотый но поверь у мы т...
1,"Да, все-таки он немного похож на него. Но мой ...",positive,да всё таки он немного похожий на он но мой ма...
2,RT @KatiaCheh: Ну ты идиотка) я испугалась за ...,positive,rt katiacheh: ну ты идиотка) я испугаться за т...
3,"RT @digger2912: ""Кто то в углу сидит и погибае...",positive,rt digger : кто то в угол сидеть и погибать от...
4,@irina_dyshkant Вот что значит страшилка :D\nН...,positive,irina_dyshkant вот что значит страшилка :d но ...

We write down the received data in format for teaching the classifier:

In [15]:
X = df.lemmas.tolist()
y = df.label.tolist()

X, y = np.array(X), np.array(y)

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.33)
print ("total train examples %s" % len(y_train))
print ("total test examples %s" % len(y_test))

total train examples 151978
total test examples 74856

In [16]:
with open('data.train.txt', 'w+') as outfile:
    for i in range(len(X_train)):
        outfile.write('__label__' + y_train[i] + ' '+ X_train[i] + '\n')


with open('test.txt', 'w+') as outfile:
    for i in range(len(X_test)):
        outfile.write('__label__' + y_test[i] + ' ' + X_test[i] + '\n')

In [17]:
classifier = fasttext.train_supervised('data.train.txt')
result = classifier.test('test.txt')

print('P@1:', result[1])
print('R@1:', result[2])
print('Number of examples:', result[0])

P@1: 0.8981243988457839
R@1: 0.8981243988457839
Number of examples: 74856